fintrac/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace fintrac.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Welcome()
        {
            return View();
        }
        public ActionResult WelcomeAdmin()
        {
            return View();
        }
        public ActionResult WelcomeAdvisor()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

fintrac/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using fintrac.Models;

namespace fintrac.Controllers
{
    public class OfferController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: /Offer/
        public ActionResult Index()
        {
            return View(db.Offers.ToList());
        }

        // GET: /Offer/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // GET: /Offer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Offer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="OId,bankName,offerTitle,offerName,offerDescription,serviceName,offerPostalCode")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                db.Offers.Add(offer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(offer);
        }

        // GET: /Offer/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // POST: /Offer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="OId,bankName,offerTitle,offerName,offerDescription,serviceName,offerPostalCode")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offer);
        }

        // GET: /Offer/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        // POST: /Offer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Offer offer = db.Offers.Find(id);
            db.Offers.Remove(offer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

fintrac/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

fintrac/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

fintrac/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Fintrac</h1>
    <p class="lead">Fintrac is third part Company that will be created to bridge the gap between financial institutions (e.g banks, insurance, investment firms) and customers</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Purpose</h2>
        <p>
            Application will provide user the ability to type a request and receive response from registered financial service advisor from different financial institutions. It will also give the user the ability to choose interested product/service from reques t amet fermentum tempus. Fusce at libero quam. Vivamus sagitti
        </p>
        <p>@Html.ActionLink("About", "./About")</p>
    </div>
    <div class="col-md-4">
        <h2>Services</h2>
        <p>uisque convallis dolor sit amet fermentum tempus. Fusce at libero quam. Vivamus sagittis tortor nec sodales molestie. Quisque pretium a libero ac dapibus. Cras in venenatis ex. Vestibulum elementum ante at libero accumsan vulputate. Curabitur at neque ac mi feugiat efficitur non ut ipsum. Nunc et porttitor ante..</p>
        <p>@Html.ActionLink("Login", "../Account/Login")</p>
    </div>
    <div class="col-md-4">
        <h2>Offers</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis rhoncus euismod odio sed blandit. Mauris ullamcorper, turpis eu convallis eleifend, nunc arcu scelerisque velit, et lobortis ligula nisl id est. Nunc felis ante, tempor nec lorem id, varius faucibus eros. Maecenas faucibus venenatis ante, eu dictum elit.</p>
        <p>@Html.ActionLink("Login", "../Account/Login")</p>
    </div>
</div>

fintrac/Views/Home/Welcome.cshtml
@model  fintrac.Models.Offer
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome</h2>

<div class="jumbotron">
    <h1>@ViewBag.Title to Fintrac</h1>
</div>
<h4>Choose your Service and Location.</h4>
<hr />
@Html.ValidationSummary()
<div class="form-group">
    @Html.LabelFor(m => m.offerPostalCode, new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        @Html.TextBoxFor(m => m.offerPostalCode, new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.serviceName, new { @class = "col-md-2 control-label" })
    <select name="serviceName">

        <option>Credit card</option>
        <option>Checking account</option>
        <option>Saving Account</option>
        <option>Mortgage</option>
        <option>Loan</option>
        @*<option>@DateTime.Now.AddYears(5).Year</option>*@

    </select>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" class="btn btn-default" value="Submit" />
    </div>
</div>

fintrac/Views/Home/WelcomeAdmin.cshtml
@{
    ViewBag.Title = "WelcomeAdmin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome Admin</h2>

fintrac/Views/Home/WelcomeAdvisor.cshtml
@{
    ViewBag.Title = "WelcomeAdvisor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome</h2>


    <button>@Html.ActionLink("Add Offer", "AddOffer", "Offer")</button> <br /><br />
    <button>@Html.ActionLink("Update Offer", "UpdateOffer", "Offer")</button> <br /><br />
    <button>@Html.ActionLink("Validate Request", "ValidateRequest", "Offer")</button> <br /><br />